# Generated by Django 5.2 on 2025-05-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Liveact', 'verbose_name_plural': 'Liveacts'},
        ),
    ]
